### ISSUE TITLE
Using BABYLON GUI

### ISSUE THREAD

**Issue by zeser78** [JohnnyDevNull/ng-babylon#3]
Hi, I try to use your template with BABYLON GUI. I have problems importing the module 'babylonjs' and 'babylonjs-gui' at the same time. Do you know why? Thanks

**Comment by JohnnyDevNull** [comment]
Hi there, sorry for my late reaction. I was not really active the past weeks on my projects. Did you found a solution? When not please could you share here your code part with the problem?

**Comment by JohnnyDevNull** [comment]
closed because of no answer
