### ISSUE TITLE
Importing Inspector as ES6 module leads to breaking code (+solution inside)

### ISSUE THREAD

**Issue by sylvix** [JohnnyDevNull/ng-babylon#5]
Hello. I'm starting to learn BabylonJS and loving it so far.

I'm really interested in creating Electron + Angular + BabylonJS game since I have mostly web-development background and was really interested that I could create games with JavaScript.

So here are motivations for my choice (in case anyone is interested):
* BabylonJS - looks pretty mature to me, I'm not sure which is better of existing WebGL frameworks yet, but I chose to pick this one for now.
* Angular - I want to leverage Dependency Injection here mostly, but also to build a level editor and I hope Angular-components style controls for adding and editing stuff will be enough.
* Electron - I want to bundle my game as a cross-platform desktop app instead of online.

I was very interested in seeing your template, but I decided to make my own and got stuck with one problem - enabling Inspector. 
I reverted to your template and this problem is also here. 

So, the official docs say to enable Inspector you just need to call:

`scene.debugLayer.show();`

However if you do this, you will get this error to the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'GUI')
ERROR TypeError: Cannot read properties of undefined (reading 'Inspector')
```
Actually when you call `show()` on a debug layer it actually downloads a bundle from Babylon CDN and runs it. And since Angular doesn't have a `BABYLON` global variable, this script can't read those from undefined.

Another thing - on GitHub page of @babylonjs/inspector there is another way:

```
import "@babylonjs/core/Debug/debugLayer";
import "@babylonjs/inspector";
```

To do this you need to also install @babylonjs/inspector library (`npm i @babylonjs/inspector@5.0.0-alpha.65`).

But those imports break TypeScript compilation even further (cut text):

```
Error: node_modules/@babylonjs/core/Engines/engine.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: GPUSupportedFeatures, GPUPredefinedColorSpace, GPU, GPUPowerPreference, GPUAdapter, GPUFeatureName, GPUDevice, etc... very long error list with different stuff
``` 

I couldn't find a way to load those libraries the intended way in Angular, so I decided to return to the first method. This is the method that I use to load the whole babylon context inside `window` so it's "visible" to that external script. I added a new method to your engine.service.ts file:

```
  private loadBabylonIntoWindow = async () => {
    window['BABYLON'] = await import("@babylonjs/core/Legacy/legacy");
    return this.scene.debugLayer.show();
  }
```
And then call it inside createScene for example:
```
void this.loadBabylonIntoWindow();
```
Now it works perfectly. But you should consider that it loads the WHOLE Babylon so the bundle won't be small. I'm doing a desktop app so it's fine but for the web it's probably better to use dynamic imports of Angular Modules (move this code out to a new module and import it conditionally, for example only in the development environment).

Hope you can improve this template further so it allows for using Inspector with less pain. Or maybe I could help anyone who was looking for the same solution.

PS. Looking at the source code of Inspector I was really shocked to see that it's made with React! I was choosing between Angular and React... Maybe it's not too late to look the other way?

**Comment by JohnnyDevNull** [comment]
Hi @sylvix,

sry for the late answer, but i have literally no time actually for investigating into integrating some stuff in the template because of other priorities. But to say, the main goal of this template project is to offer a pretty simple Angular starter with not much logic or other libraries integrated.

So i would not integrate it here in this simple starter, but a fork with a example could be a good idea.

Best Regards!

**Comment by sylvix** [comment]
There are no other libraries involved, it's debug layer of  the same babylonjs. I still see "babylon" in the title of this project. Don't you use it?
